### ISSUE TITLE
[Crash] [1.18.2] - right click on anvil stick - java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by xR4YM0ND** [dvitski/onastick-archive#6]
Crashes client when right click on anvil stick

Fabric 1.18.2 - 0.13.3 
Lot of mods are present

[Latest.Log](https://gist.github.com/SpigotDE/75c10d9ae9e5f5733c60c545dce7d579)
[Crash Report](https://gist.github.com/SpigotDE/b1c1247d802d1f97fea283028cfdf765)

**Comment by dvitski** [comment]
Crash caused by [bclib](https://github.com/paulevsGitch/BCLib)
